# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50ee949a05b7fc4c4c079c598ef20119d24102601be82e9f5f5555575fa00ab55f7d6ea953b84f4893dd83cc301f43d545da41be39ee05fde6534ae3390171bf

test:
  secret_key_base: f70d9fa611375e64da2ab44ee3f3b4e163a2914286601673b6fb59ed91e837f5f8b1db034f5669770ee10b4440a50b3a192d72648f4ab188cfb2d04965be32e0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
